# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181023_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default='', max_length=50, unique=True),
        ),
    ]
